on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build Sheet
    runs-on: ubuntu-latest

    steps:
      - name: Install CNS11643 fonts
        uses: RisingInIris2017/cjk-fonts-action@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update build time
        run: date > build_time.txt
        
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: index.typ
          font-dir: /usr/share/fonts

      - name: Rename
        run: |
          mv index.pdf sheet.pdf
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            sheet.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ env.DATE }}"
          files: "sheet.pdf"
        